spring:
  application:
    name: spring-boot-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: http://git@github.com:Shivakant6387/spring-boot-properties.git
server:
  port: 12909